[build]
  command = "npm run build:client && npm run build:server"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"
